CREATE OR REPLACE TABLE mart_credit_risk_features AS
SELECT
    applicant.*,
    bureau.bureau_credit_count,
    bureau.active_credit_count,
    bureau.closed_credit_count,
    bureau.overdue_credit_count,
    bureau.max_credit_day_overdue,
    bureau.total_credit_sum,
    bureau.avg_credit_sum,
    bureau.total_credit_debt,
    bureau.total_credit_limit,
    bureau.total_credit_overdue,
    bureau.avg_days_credit,
    bureau.earliest_days_credit,
    bureau.latest_days_credit,
    bureau.avg_days_credit_enddate,
    bureau.avg_days_enddate_fact,
    bureau_balance.bureau_balance_month_count,
    bureau_balance.bureau_balance_bureau_count,
    bureau_balance.bureau_balance_closed_month_count,
    bureau_balance.bureau_balance_unknown_month_count,
    bureau_balance.bureau_balance_dpd_0_count,
    bureau_balance.bureau_balance_dpd_1plus_count,
    bureau_balance.bureau_balance_dpd_2plus_count,
    bureau_balance.bureau_balance_dpd_5plus_count,
    bureau_balance.bureau_balance_max_status,
    bureau_balance.bureau_balance_avg_numeric_status,
    bureau_balance.bureau_balance_latest_month,
    bureau_balance.bureau_balance_earliest_month,
    bureau_balance.bureau_balance_recent_month_count,
    bureau_balance.bureau_balance_recent_known_month_count,
    bureau_balance.bureau_balance_recent_dpd_1plus_count,
    bureau_balance.bureau_balance_dpd_1plus_rate,
    bureau_balance.bureau_balance_dpd_2plus_rate,
    bureau_balance.bureau_balance_recent_dpd_1plus_rate,
    pos_cash.pos_cash_month_count,
    pos_cash.pos_cash_contract_count,
    pos_cash.pos_cash_active_month_count,
    pos_cash.pos_cash_completed_month_count,
    pos_cash.pos_cash_problem_status_month_count,
    pos_cash.pos_cash_dpd_month_count,
    pos_cash.pos_cash_dpd_def_month_count,
    pos_cash.pos_cash_max_dpd,
    pos_cash.pos_cash_max_dpd_def,
    pos_cash.pos_cash_avg_dpd,
    pos_cash.pos_cash_avg_dpd_def,
    pos_cash.pos_cash_avg_instalment_count,
    pos_cash.pos_cash_avg_future_installments,
    pos_cash.pos_cash_latest_month,
    pos_cash.pos_cash_earliest_month,
    pos_cash.pos_cash_recent_month_count,
    pos_cash.pos_cash_recent_dpd_month_count,
    pos_cash.pos_cash_completed_month_rate,
    pos_cash.pos_cash_dpd_month_rate,
    pos_cash.pos_cash_dpd_def_month_rate,
    pos_cash.pos_cash_recent_dpd_month_rate,
    credit_card.credit_card_month_count,
    credit_card.credit_card_contract_count,
    credit_card.credit_card_active_month_count,
    credit_card.credit_card_completed_month_count,
    credit_card.credit_card_problem_status_month_count,
    credit_card.credit_card_dpd_month_count,
    credit_card.credit_card_dpd_def_month_count,
    credit_card.credit_card_max_dpd,
    credit_card.credit_card_max_dpd_def,
    credit_card.credit_card_avg_dpd,
    credit_card.credit_card_avg_dpd_def,
    credit_card.credit_card_avg_balance,
    credit_card.credit_card_max_balance,
    credit_card.credit_card_avg_credit_limit,
    credit_card.credit_card_max_credit_limit,
    credit_card.credit_card_balance_to_limit_ratio,
    credit_card.credit_card_avg_credit_utilization,
    credit_card.credit_card_avg_drawings_current,
    credit_card.credit_card_total_drawings_current,
    credit_card.credit_card_avg_drawing_count,
    credit_card.credit_card_total_drawing_count,
    credit_card.credit_card_avg_total_receivable,
    credit_card.credit_card_total_receivable,
    credit_card.credit_card_payment_to_min_ratio,
    credit_card.credit_card_total_payment_to_min_ratio,
    credit_card.credit_card_latest_month,
    credit_card.credit_card_earliest_month,
    credit_card.credit_card_recent_month_count,
    credit_card.credit_card_recent_dpd_month_count,
    credit_card.credit_card_completed_month_rate,
    credit_card.credit_card_dpd_month_rate,
    credit_card.credit_card_dpd_def_month_rate,
    credit_card.credit_card_recent_dpd_month_rate,
    recency_deterioration.bureau_balance_recent_dpd_rate_delta,
    recency_deterioration.bureau_balance_recent_status_delta,
    recency_deterioration.pos_cash_recent_dpd_rate_delta,
    recency_deterioration.pos_cash_remaining_installment_ratio_delta,
    recency_deterioration.credit_card_recent_utilization_delta,
    recency_deterioration.credit_card_recent_balance_ratio_delta,
    recency_deterioration.credit_card_recent_drawings_ratio_delta,
    recency_deterioration.credit_card_recent_dpd_rate_delta,
    last_k_temporal.installments_last_3_late_payment_rate,
    last_k_temporal.installments_last_3_underpayment_rate,
    last_k_temporal.installments_last_3_avg_payment_delay_days,
    last_k_temporal.installments_last_3_payment_amount_ratio,
    last_k_temporal.installments_last_payment_delay_days,
    last_k_temporal.installments_last_payment_ratio,
    last_k_temporal.pos_cash_last_3_dpd_rate,
    last_k_temporal.pos_cash_last_3_dpd_def_rate,
    last_k_temporal.pos_cash_last_3_future_installment_ratio,
    last_k_temporal.pos_cash_last_3_dpd_rate_delta,
    last_k_temporal.pos_cash_last_loan_dpd_rate,
    last_k_temporal.credit_card_last_3_credit_utilization,
    last_k_temporal.credit_card_last_3_payment_to_min_ratio,
    last_k_temporal.credit_card_last_3_drawing_count,
    last_k_temporal.credit_card_last_3_dpd_rate,
    last_k_temporal.credit_card_last_3_utilization_delta,
    previous.previous_application_count,
    previous.approved_application_count,
    previous.refused_application_count,
    previous.canceled_application_count,
    previous.approval_rate,
    previous.refusal_rate,
    previous.avg_application_amount,
    previous.avg_previous_credit_amount,
    previous.total_previous_credit_amount,
    previous.avg_credit_to_application_ratio,
    previous.avg_days_decision,
    previous.earliest_days_decision,
    previous.latest_days_decision,
    installments.installment_payment_count,
    installments.late_payment_count,
    installments.avg_payment_delay_days,
    installments.max_payment_delay_days,
    installments.underpayment_count,
    installments.total_instalment_amount,
    installments.total_payment_amount,
    installments.payment_amount_ratio,
    installments.avg_payment_to_instalment_ratio,
    risk_pressure.external_score_credit_pressure,
    risk_pressure.external_score_annuity_pressure,
    risk_pressure.bureau_debt_to_income_ratio,
    risk_pressure.payment_shortfall_ratio
FROM f_applicant_static AS applicant
LEFT JOIN f_bureau_agg AS bureau
    ON applicant.SK_ID_CURR = bureau.SK_ID_CURR
LEFT JOIN f_bureau_balance_agg AS bureau_balance
    ON applicant.SK_ID_CURR = bureau_balance.SK_ID_CURR
LEFT JOIN f_pos_cash_agg AS pos_cash
    ON applicant.SK_ID_CURR = pos_cash.SK_ID_CURR
LEFT JOIN f_credit_card_agg AS credit_card
    ON applicant.SK_ID_CURR = credit_card.SK_ID_CURR
LEFT JOIN f_previous_application_agg AS previous
    ON applicant.SK_ID_CURR = previous.SK_ID_CURR
LEFT JOIN f_installments_agg AS installments
    ON applicant.SK_ID_CURR = installments.SK_ID_CURR
LEFT JOIN f_risk_pressure_features AS risk_pressure
    ON applicant.SK_ID_CURR = risk_pressure.SK_ID_CURR
    AND applicant.source_population = risk_pressure.source_population
LEFT JOIN f_recency_deterioration_features AS recency_deterioration
    ON applicant.SK_ID_CURR = recency_deterioration.SK_ID_CURR
    AND applicant.source_population = recency_deterioration.source_population
LEFT JOIN f_last_k_temporal_features AS last_k_temporal
    ON applicant.SK_ID_CURR = last_k_temporal.SK_ID_CURR
    AND applicant.source_population = last_k_temporal.source_population;
